export const PRODUCTS_ACTION_TYPES = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS_START: "SET_PRODUCTS_START",
  SET_PRODUCTS_SUCCESS: "SET_PRODUCTS_SUCCESS",
  SET_PRODUCTS_FAILED: "SET_PRODUCTS_FAILED",
  SET_PRODUCT_NAME: "SET_PRODUCT_NAME",
  // SET_PRODUCT_DETAILS: "SET_PRODUCT_DETAILS",
};
